### ISSUE TITLE
Having Problem while Setting Dev Environment

### ISSUE THREAD

**Issue by ayushkoli772** [cytoscape/cytoscape-web#136]
Can you please clarify what steps I have to carry for this Build Instruction: 

> dev: run a dev server that watches code changes, open localhost:5500 in your web browser. By default this app points to [NDEx dev server] (https://dev.ndexbio.org/), please create an account on the NDEx dev server with a email that links to your Google account before trying to setup your own dev environment for Cytoscape Web.

I have created a account on NDEx dev. 

Whenever I run `yarn dev` and open `localhost:5500` it shows blank screen. Are there any additional considerations that need to be followed?

Thank you for your time and consideration

**Comment by GAOChengzhan** [comment]
For now it might have some issues with the redirect url in our project. Please try `localhost:5500/cytoscape/` instead of `localhost:5500`. And please be careful that if you refresh the page, you have to manually type `localhost:5500/cytoscape/` again. This is a temporary solution and this bug would be solved soon.

**Comment by jingjingbic** [comment]
> Can you please clarify what steps I have to carry for this Build Instruction:
> 
> > dev: run a dev server that watches code changes, open localhost:5500 in your web browser. By default this app points to [NDEx dev server] (https://dev.ndexbio.org/), please create an account on the NDEx dev server with a email that links to your Google account before trying to setup your own dev environment for Cytoscape Web.
> 
> I have created a account on NDEx dev.
> 
> Whenever I run `yarn dev` and open `localhost:5500` it shows blank screen. Are there any additional considerations that need to be followed?
> 
> Thank you for your time and consideration

@ayushkoli772  Could you try again? We have updated the config file and it should run on 'localhost:5500' if you check the dev branch.

**Comment by ayushkoli772** [comment]
Thank you @jingjingbic @GAOChengzhan, its working now
